### ISSUE TITLE
Use local boost and compile tests only when required 

### ISSUE THREAD

**Issue by Rohit-Kakodkar** [PrincetonUniversity/specfem2d_kokkos#63]
# CMAKE updates for faster compilation:

1) Use local boost directory when provided - Currently a version of boost is downloaded for every new compilation which increases compile times
2) Compile tests only when required - Only compile tests when BUILD_TESTS flags is ON

**Comment by sirpipat** [comment]
I will do it

**Comment by lsawade** [comment]
@sirpipat How about I do 1 and you do 2?

**Comment by sirpipat** [comment]
@lsawade It sounds like a good idea.
